alter table public.recipes
  add column if not exists meal_type text,
  add column if not exists diet text,
  add column if not exists region text,
  add column if not exists difficulty text,
  add column if not exists spice_level text;

create unique index if not exists recipes_name_unique_idx on public.recipes (name);

insert into public.recipes (name, cuisine, prep_time_minutes, servings, instructions, ingredients, meal_type, diet, region, difficulty, spice_level)
values
  ('Masala Dosa', 'Indian', 40, 4, '1. Boil potatoes, mash and saute with mustard seeds, curry leaves, onion and turmeric.
2. Spread dosa batter thin on a hot greased pan.
3. Drizzle oil, cook until golden and crisp.
4. Fill with potato masala, fold and serve with chutney and sambar.', '[{"name":"dosa batter","quantity_text":"3 cups","optional":false},{"name":"potato","quantity_text":"4","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"mustard seeds","quantity_text":"1 tsp","optional":false},{"name":"curry leaves","quantity_text":"10","optional":false},{"name":"turmeric","quantity_text":"1/2 tsp","optional":false},{"name":"green chili","quantity_text":"2","optional":false},{"name":"oil","quantity_text":"3 tbsp","optional":false},{"name":"coconut chutney","quantity_text":"to serve","optional":true}]'::jsonb, 'breakfast', 'vegetarian', 'South Indian', 'medium', 'mild'),
  ('Amritsari Chole Kulche', 'Indian', 60, 4, '1. Pressure cook soaked chickpeas with tea bag and salt until soft.
2. Saute onion, ginger, garlic and tomato; add chole masala, amchur and chili.
3. Add chickpeas, simmer 15 minutes until thick.
4. Toast kulcha with butter and serve with chole, onion and lemon.', '[{"name":"chickpeas","quantity_text":"2 cups","optional":false},{"name":"onion","quantity_text":"2","optional":false},{"name":"tomato","quantity_text":"2","optional":false},{"name":"ginger","quantity_text":"1 inch","optional":false},{"name":"garlic","quantity_text":"4 cloves","optional":false},{"name":"chole masala","quantity_text":"2 tbsp","optional":false},{"name":"amchur","quantity_text":"1 tsp","optional":false},{"name":"kulcha","quantity_text":"4","optional":false},{"name":"butter","quantity_text":"2 tbsp","optional":false},{"name":"lemon","quantity_text":"1","optional":true}]'::jsonb, 'lunch', 'vegetarian', 'Punjabi', 'medium', 'medium'),
  ('Kerala Appam with Vegetable Stew', 'Indian', 45, 4, '1. Pour appam batter into a hot appachatti, swirl to form thin edges, cover and cook.
2. Saute onion, ginger, green chili and curry leaves in coconut oil.
3. Add carrot, beans, potato and thin coconut milk; simmer until tender.
4. Finish with thick coconut milk and pepper. Serve with appams.', '[{"name":"appam batter","quantity_text":"3 cups","optional":false},{"name":"coconut milk","quantity_text":"2 cups","optional":false},{"name":"carrot","quantity_text":"1","optional":false},{"name":"green beans","quantity_text":"1 cup","optional":false},{"name":"potato","quantity_text":"1","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"ginger","quantity_text":"1 inch","optional":false},{"name":"green chili","quantity_text":"2","optional":false},{"name":"curry leaves","quantity_text":"10","optional":false},{"name":"coconut oil","quantity_text":"2 tbsp","optional":false},{"name":"black pepper","quantity_text":"1/2 tsp","optional":false}]'::jsonb, 'breakfast', 'vegan', 'Kerala', 'medium', 'mild'),
  ('Hyderabadi Chicken Dum Biryani', 'Indian', 120, 6, '1. Marinate chicken in yogurt, ginger garlic paste, biryani masala, chili, mint and fried onions for 2 hours.
2. Parboil basmati rice with whole spices to 70%.
3. Layer chicken and rice in a heavy pot, top with saffron milk, ghee and mint.
4. Seal with dough or foil; cook on dum 35 minutes on low heat.', '[{"name":"chicken","quantity_text":"1 kg","optional":false},{"name":"basmati rice","quantity_text":"3 cups","optional":false},{"name":"yogurt","quantity_text":"1 cup","optional":false},{"name":"onion","quantity_text":"3","optional":false},{"name":"ginger garlic paste","quantity_text":"2 tbsp","optional":false},{"name":"biryani masala","quantity_text":"2 tbsp","optional":false},{"name":"mint","quantity_text":"1 cup","optional":false},{"name":"coriander leaves","quantity_text":"1/2 cup","optional":false},{"name":"saffron","quantity_text":"a pinch","optional":true},{"name":"ghee","quantity_text":"3 tbsp","optional":false},{"name":"green chili","quantity_text":"4","optional":false},{"name":"lemon","quantity_text":"1","optional":false}]'::jsonb, 'dinner', 'non-vegetarian', 'Hyderabadi', 'hard', 'medium'),
  ('Shorshe Ilish', 'Indian', 30, 4, '1. Rub hilsa pieces with salt and turmeric.
2. Grind mustard seeds with green chili and a little water to a paste.
3. Heat mustard oil, add nigella seeds, then mustard paste, turmeric and water.
4. Slide in fish, cover and simmer 10 minutes. Serve with steamed rice.', '[{"name":"hilsa fish","quantity_text":"500 g","optional":false},{"name":"mustard seeds","quantity_text":"3 tbsp","optional":false},{"name":"mustard oil","quantity_text":"4 tbsp","optional":false},{"name":"green chili","quantity_text":"4","optional":false},{"name":"turmeric","quantity_text":"1 tsp","optional":false},{"name":"nigella seeds","quantity_text":"1/2 tsp","optional":false},{"name":"salt","quantity_text":"to taste","optional":false}]'::jsonb, 'lunch', 'non-vegetarian', 'Bengali', 'medium', 'hot'),
  ('Khaman Dhokla', 'Indian', 30, 4, '1. Whisk besan, yogurt, water, ginger chili paste, turmeric, sugar and salt to a smooth batter.
2. Stir in fruit salt, pour into a greased tin and steam 15 minutes.
3. Temper mustard seeds, curry leaves and green chili in oil with a little water and sugar; pour over.
4. Cut into squares and garnish with coriander and coconut.', '[{"name":"besan","quantity_text":"1.5 cups","optional":false},{"name":"yogurt","quantity_text":"1/2 cup","optional":false},{"name":"fruit salt","quantity_text":"1 tsp","optional":false},{"name":"ginger","quantity_text":"1 inch","optional":false},{"name":"green chili","quantity_text":"3","optional":false},{"name":"sugar","quantity_text":"2 tbsp","optional":false},{"name":"mustard seeds","quantity_text":"1 tsp","optional":false},{"name":"curry leaves","quantity_text":"8","optional":false},{"name":"oil","quantity_text":"2 tbsp","optional":false},{"name":"grated coconut","quantity_text":"2 tbsp","optional":true},{"name":"coriander leaves","quantity_text":"2 tbsp","optional":true}]'::jsonb, 'snack', 'vegetarian', 'Gujarati', 'easy', 'mild'),
  ('Misal Pav', 'Indian', 50, 4, '1. Pressure cook sprouted moth beans with turmeric and salt.
2. Fry onion, garlic, ginger, coconut and goda masala; grind to a paste.
3. Cook paste in oil with red chili powder, add sprouts and water; simmer to a thin spicy curry.
4. Serve in bowls topped with farsan, onion, coriander and lemon, with buttered pav.', '[{"name":"moth bean sprouts","quantity_text":"2 cups","optional":false},{"name":"onion","quantity_text":"2","optional":false},{"name":"garlic","quantity_text":"6 cloves","optional":false},{"name":"grated coconut","quantity_text":"1/2 cup","optional":false},{"name":"goda masala","quantity_text":"2 tbsp","optional":false},{"name":"red chili powder","quantity_text":"2 tsp","optional":false},{"name":"farsan","quantity_text":"1 cup","optional":false},{"name":"pav","quantity_text":"8","optional":false},{"name":"lemon","quantity_text":"1","optional":false},{"name":"coriander leaves","quantity_text":"1/4 cup","optional":true},{"name":"oil","quantity_text":"3 tbsp","optional":false}]'::jsonb, 'breakfast', 'vegetarian', 'Maharashtrian', 'medium', 'hot'),
  ('Dal Baati Churma', 'Indian', 90, 4, '1. Knead wheat flour, semolina, ghee and salt into stiff dough; shape balls and bake at 180C for 35 minutes.
2. Cook mixed dals with turmeric; temper with ghee, cumin, garlic, chili and garam masala.
3. Crush a few baatis, mix with ghee, jaggery and cardamom for churma.
4. Dip baatis in ghee and serve with dal and churma.', '[{"name":"wheat flour","quantity_text":"2 cups","optional":false},{"name":"semolina","quantity_text":"1/4 cup","optional":false},{"name":"ghee","quantity_text":"1/2 cup","optional":false},{"name":"toor dal","quantity_text":"1/2 cup","optional":false},{"name":"moong dal","quantity_text":"1/4 cup","optional":false},{"name":"chana dal","quantity_text":"1/4 cup","optional":false},{"name":"garlic","quantity_text":"5 cloves","optional":false},{"name":"cumin seeds","quantity_text":"1 tsp","optional":false},{"name":"red chili powder","quantity_text":"1 tsp","optional":false},{"name":"garam masala","quantity_text":"1 tsp","optional":false},{"name":"jaggery","quantity_text":"1/3 cup","optional":false},{"name":"cardamom","quantity_text":"4 pods","optional":false}]'::jsonb, 'lunch', 'vegetarian', 'Rajasthani', 'hard', 'medium'),
  ('Goan Prawn Curry', 'Indian', 35, 4, '1. Grind coconut, dried red chilies, coriander seeds, cumin, turmeric, garlic and tamarind to a smooth paste.
2. Saute onion in oil, add the paste and cook 5 minutes.
3. Add water and kokum, simmer 10 minutes.
4. Add prawns, cook 4 minutes and serve with rice.', '[{"name":"prawns","quantity_text":"500 g","optional":false},{"name":"grated coconut","quantity_text":"1 cup","optional":false},{"name":"dried red chili","quantity_text":"6","optional":false},{"name":"coriander seeds","quantity_text":"1 tbsp","optional":false},{"name":"cumin seeds","quantity_text":"1 tsp","optional":false},{"name":"turmeric","quantity_text":"1/2 tsp","optional":false},{"name":"garlic","quantity_text":"5 cloves","optional":false},{"name":"tamarind","quantity_text":"small ball","optional":false},{"name":"kokum","quantity_text":"3 pieces","optional":true},{"name":"onion","quantity_text":"1","optional":false},{"name":"oil","quantity_text":"2 tbsp","optional":false}]'::jsonb, 'dinner', 'non-vegetarian', 'Goan', 'medium', 'hot'),
  ('Veg Hakka Noodles', 'Indian', 25, 3, '1. Boil noodles al dente, drain and toss with a little oil.
2. Stir fry garlic, ginger, cabbage, carrot, capsicum and spring onion on high heat.
3. Add soy sauce, vinegar, chili sauce and pepper.
4. Toss in noodles, mix well and serve hot.', '[{"name":"hakka noodles","quantity_text":"250 g","optional":false},{"name":"cabbage","quantity_text":"1 cup","optional":false},{"name":"carrot","quantity_text":"1","optional":false},{"name":"capsicum","quantity_text":"1","optional":false},{"name":"spring onion","quantity_text":"4","optional":false},{"name":"garlic","quantity_text":"4 cloves","optional":false},{"name":"soy sauce","quantity_text":"2 tbsp","optional":false},{"name":"vinegar","quantity_text":"1 tbsp","optional":false},{"name":"chili sauce","quantity_text":"1 tbsp","optional":true},{"name":"oil","quantity_text":"2 tbsp","optional":false},{"name":"black pepper","quantity_text":"1/2 tsp","optional":false}]'::jsonb, 'dinner', 'vegan', 'Indo-Chinese', 'easy', 'medium'),
  ('Pani Puri', 'Indian', 40, 4, '1. Blend mint, coriander, green chili, ginger, tamarind, chaat masala, black salt and cold water for the pani.
2. Mix boiled potato, chickpeas, onion, chaat masala and salt for filling.
3. Crack the top of each puri, add filling and a spoon of tamarind chutney.
4. Dunk in pani and eat immediately.', '[{"name":"puri","quantity_text":"40","optional":false},{"name":"mint","quantity_text":"1 cup","optional":false},{"name":"coriander leaves","quantity_text":"1 cup","optional":false},{"name":"green chili","quantity_text":"3","optional":false},{"name":"tamarind","quantity_text":"2 tbsp","optional":false},{"name":"chaat masala","quantity_text":"2 tsp","optional":false},{"name":"black salt","quantity_text":"1 tsp","optional":false},{"name":"potato","quantity_text":"2","optional":false},{"name":"chickpeas","quantity_text":"1/2 cup","optional":false},{"name":"onion","quantity_text":"1","optional":true},{"name":"tamarind chutney","quantity_text":"1/2 cup","optional":false}]'::jsonb, 'snack', 'vegetarian', 'Street Food', 'medium', 'medium'),
  ('Masala Chai', 'Indian', 10, 2, '1. Crush ginger, cardamom, cloves and cinnamon.
2. Boil water with the spices for 2 minutes.
3. Add tea leaves and sugar, boil 1 minute.
4. Add milk, simmer 2 minutes, strain and serve.', '[{"name":"tea leaves","quantity_text":"2 tsp","optional":false},{"name":"milk","quantity_text":"1 cup","optional":false},{"name":"water","quantity_text":"1 cup","optional":false},{"name":"ginger","quantity_text":"1 inch","optional":false},{"name":"cardamom","quantity_text":"3 pods","optional":false},{"name":"cloves","quantity_text":"2","optional":true},{"name":"cinnamon","quantity_text":"small stick","optional":true},{"name":"sugar","quantity_text":"2 tsp","optional":false}]'::jsonb, 'beverage', 'vegetarian', 'Pan-Indian', 'easy', 'none'),
  ('Gulab Jamun', 'Indian', 45, 6, '1. Boil sugar, water, cardamom and rose water into a sticky syrup; keep warm.
2. Knead milk powder, flour, baking soda, ghee and milk into a soft dough; roll smooth balls.
3. Deep fry on low heat until deep golden.
4. Soak in warm syrup for at least 1 hour.', '[{"name":"milk powder","quantity_text":"1 cup","optional":false},{"name":"all purpose flour","quantity_text":"1/4 cup","optional":false},{"name":"baking soda","quantity_text":"1/4 tsp","optional":false},{"name":"ghee","quantity_text":"1 tbsp","optional":false},{"name":"milk","quantity_text":"1/4 cup","optional":false},{"name":"sugar","quantity_text":"1.5 cups","optional":false},{"name":"cardamom","quantity_text":"4 pods","optional":false},{"name":"rose water","quantity_text":"1 tsp","optional":true},{"name":"oil","quantity_text":"for frying","optional":false}]'::jsonb, 'dessert', 'vegetarian', 'Pan-Indian', 'medium', 'none'),
  ('Rava Upma', 'Indian', 20, 3, '1. Dry roast semolina until fragrant; set aside.
2. Temper mustard seeds, urad dal, curry leaves, green chili, ginger and onion in oil.
3. Add 3 cups hot water and salt; bring to boil.
4. Stir in semolina, cook covered 3 minutes, finish with ghee and lemon.', '[{"name":"semolina","quantity_text":"1 cup","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"green chili","quantity_text":"2","optional":false},{"name":"ginger","quantity_text":"1 inch","optional":false},{"name":"mustard seeds","quantity_text":"1 tsp","optional":false},{"name":"urad dal","quantity_text":"1 tsp","optional":false},{"name":"curry leaves","quantity_text":"8","optional":false},{"name":"oil","quantity_text":"2 tbsp","optional":false},{"name":"ghee","quantity_text":"1 tsp","optional":true},{"name":"lemon","quantity_text":"1/2","optional":true},{"name":"cashews","quantity_text":"8","optional":true}]'::jsonb, 'breakfast', 'vegetarian', 'South Indian', 'easy', 'mild'),
  ('Sarson Ka Saag with Makki Roti', 'Indian', 75, 4, '1. Pressure cook mustard greens, spinach and bathua with ginger, garlic and green chili.
2. Blend coarsely, return to pot with maize flour and simmer 20 minutes.
3. Temper onion and dried red chili in ghee; pour over saag.
4. Pat maize flour dough into rotis, cook on tawa with ghee. Serve with jaggery.', '[{"name":"mustard greens","quantity_text":"500 g","optional":false},{"name":"spinach","quantity_text":"250 g","optional":false},{"name":"maize flour","quantity_text":"2 cups","optional":false},{"name":"ginger","quantity_text":"2 inch","optional":false},{"name":"garlic","quantity_text":"6 cloves","optional":false},{"name":"green chili","quantity_text":"3","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"ghee","quantity_text":"4 tbsp","optional":false},{"name":"dried red chili","quantity_text":"2","optional":true},{"name":"jaggery","quantity_text":"to serve","optional":true}]'::jsonb, 'dinner', 'vegetarian', 'Punjabi', 'medium', 'medium'),
  ('Puttu with Kadala Curry', 'Indian', 50, 4, '1. Moisten rice flour with salted water to a crumbly texture; layer with grated coconut in puttu maker and steam 8 minutes.
2. Pressure cook soaked black chickpeas until soft.
3. Roast coconut, shallots, coriander seeds and chili; grind to paste.
4. Simmer chickpeas with paste and garam masala; serve with puttu.', '[{"name":"rice flour","quantity_text":"2 cups","optional":false},{"name":"grated coconut","quantity_text":"1.5 cups","optional":false},{"name":"black chickpeas","quantity_text":"1.5 cups","optional":false},{"name":"shallots","quantity_text":"8","optional":false},{"name":"coriander seeds","quantity_text":"1 tbsp","optional":false},{"name":"dried red chili","quantity_text":"4","optional":false},{"name":"garam masala","quantity_text":"1 tsp","optional":false},{"name":"curry leaves","quantity_text":"10","optional":false},{"name":"coconut oil","quantity_text":"2 tbsp","optional":false}]'::jsonb, 'breakfast', 'vegan', 'Kerala', 'medium', 'medium'),
  ('Mirchi Ka Salan', 'Indian', 40, 4, '1. Fry slit large green chilies lightly and set aside.
2. Roast peanuts, sesame seeds, coconut and cumin; grind with onion to a paste.
3. Cook paste in oil with ginger garlic paste, turmeric and chili powder.
4. Add tamarind water and jaggery, simmer, add chilies and cook 10 minutes.', '[{"name":"large green chili","quantity_text":"10","optional":false},{"name":"peanuts","quantity_text":"1/2 cup","optional":false},{"name":"sesame seeds","quantity_text":"2 tbsp","optional":false},{"name":"grated coconut","quantity_text":"1/4 cup","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"ginger garlic paste","quantity_text":"1 tbsp","optional":false},{"name":"tamarind","quantity_text":"2 tbsp","optional":false},{"name":"jaggery","quantity_text":"1 tsp","optional":true},{"name":"cumin seeds","quantity_text":"1 tsp","optional":false},{"name":"oil","quantity_text":"4 tbsp","optional":false}]'::jsonb, 'dinner', 'vegan', 'Hyderabadi', 'medium', 'hot'),
  ('Mishti Doi', 'Indian', 20, 4, '1. Boil milk and reduce by a third.
2. Caramelize half the sugar, add to milk with remaining sugar and stir.
3. Cool to lukewarm, whisk in yogurt starter.
4. Pour into clay pots and set undisturbed in a warm place 8 hours; chill.', '[{"name":"milk","quantity_text":"1 liter","optional":false},{"name":"sugar","quantity_text":"3/4 cup","optional":false},{"name":"yogurt","quantity_text":"3 tbsp","optional":false},{"name":"cardamom","quantity_text":"2 pods","optional":true}]'::jsonb, 'dessert', 'vegetarian', 'Bengali', 'easy', 'none'),
  ('Undhiyu', 'Indian', 90, 6, '1. Mix besan, coriander, coconut, garlic, ginger, chili, sugar and lemon; stuff into small brinjals and potatoes; make methi muthia dumplings and fry.
2. Layer surti papdi, purple yam, sweet potato, stuffed vegetables and muthia in a heavy pot with oil, ajwain and hing.
3. Cover and cook on low 40 minutes without stirring.
4. Garnish with coriander and coconut.', '[{"name":"surti papdi","quantity_text":"2 cups","optional":false},{"name":"baby brinjal","quantity_text":"6","optional":false},{"name":"baby potato","quantity_text":"6","optional":false},{"name":"purple yam","quantity_text":"1 cup","optional":false},{"name":"sweet potato","quantity_text":"1","optional":false},{"name":"besan","quantity_text":"1/2 cup","optional":false},{"name":"fenugreek leaves","quantity_text":"1 cup","optional":false},{"name":"grated coconut","quantity_text":"1/2 cup","optional":false},{"name":"coriander leaves","quantity_text":"1 cup","optional":false},{"name":"green chili","quantity_text":"4","optional":false},{"name":"ajwain","quantity_text":"1 tsp","optional":false},{"name":"oil","quantity_text":"1/2 cup","optional":false}]'::jsonb, 'dinner', 'vegetarian', 'Gujarati', 'hard', 'medium'),
  ('Vada Pav', 'Indian', 40, 4, '1. Mash boiled potatoes with sauteed mustard seeds, garlic, green chili, turmeric and curry leaves; shape into balls.
2. Dip in besan batter and deep fry golden.
3. Blend garlic, dried coconut and red chili for dry chutney.
4. Slice pav, spread chutneys, tuck in vada and serve with fried green chili.', '[{"name":"potato","quantity_text":"4","optional":false},{"name":"pav","quantity_text":"4","optional":false},{"name":"besan","quantity_text":"1 cup","optional":false},{"name":"garlic","quantity_text":"8 cloves","optional":false},{"name":"green chili","quantity_text":"4","optional":false},{"name":"mustard seeds","quantity_text":"1 tsp","optional":false},{"name":"turmeric","quantity_text":"1/2 tsp","optional":false},{"name":"curry leaves","quantity_text":"8","optional":false},{"name":"dry coconut","quantity_text":"1/4 cup","optional":false},{"name":"red chili powder","quantity_text":"1 tbsp","optional":false},{"name":"oil","quantity_text":"for frying","optional":false}]'::jsonb, 'snack', 'vegetarian', 'Maharashtrian', 'medium', 'hot'),
  ('Laal Maas', 'Indian', 80, 4, '1. Soak Mathania red chilies and grind to a paste.
2. Brown onions in ghee, add garlic, mutton and sear well.
3. Add chili paste, yogurt, coriander powder and salt; cook until oil separates.
4. Add water, cover and simmer 45 minutes until tender. Finish with garam masala.', '[{"name":"mutton","quantity_text":"750 g","optional":false},{"name":"dried red chili","quantity_text":"12","optional":false},{"name":"onion","quantity_text":"3","optional":false},{"name":"garlic","quantity_text":"10 cloves","optional":false},{"name":"yogurt","quantity_text":"1/2 cup","optional":false},{"name":"ghee","quantity_text":"4 tbsp","optional":false},{"name":"coriander powder","quantity_text":"1 tbsp","optional":false},{"name":"garam masala","quantity_text":"1 tsp","optional":false},{"name":"cloves","quantity_text":"4","optional":true}]'::jsonb, 'dinner', 'non-vegetarian', 'Rajasthani', 'medium', 'hot'),
  ('Chicken Cafreal', 'Indian', 50, 4, '1. Blend coriander leaves, green chili, ginger, garlic, cumin, cinnamon, cloves, pepper, vinegar and lemon to a paste.
2. Marinate chicken in the paste for at least 1 hour.
3. Pan fry chicken in oil on medium heat, turning, until cooked and charred at edges.
4. Serve with lemon wedges and potato wedges.', '[{"name":"chicken","quantity_text":"800 g","optional":false},{"name":"coriander leaves","quantity_text":"2 cups","optional":false},{"name":"green chili","quantity_text":"6","optional":false},{"name":"ginger","quantity_text":"2 inch","optional":false},{"name":"garlic","quantity_text":"8 cloves","optional":false},{"name":"cumin seeds","quantity_text":"1 tsp","optional":false},{"name":"cinnamon","quantity_text":"small stick","optional":false},{"name":"cloves","quantity_text":"4","optional":false},{"name":"vinegar","quantity_text":"2 tbsp","optional":false},{"name":"lemon","quantity_text":"1","optional":false},{"name":"oil","quantity_text":"3 tbsp","optional":false}]'::jsonb, 'dinner', 'non-vegetarian', 'Goan', 'medium', 'hot'),
  ('Gobi Manchurian', 'Indian', 35, 4, '1. Coat cauliflower florets in a batter of cornflour, flour, ginger garlic paste and pepper; deep fry crisp.
2. Saute garlic, ginger, green chili and spring onion in oil.
3. Add soy sauce, chili sauce, ketchup, vinegar and a cornflour slurry; cook until glossy.
4. Toss florets in sauce and garnish with spring onion greens.', '[{"name":"cauliflower","quantity_text":"1 medium","optional":false},{"name":"cornflour","quantity_text":"1/2 cup","optional":false},{"name":"all purpose flour","quantity_text":"1/4 cup","optional":false},{"name":"garlic","quantity_text":"6 cloves","optional":false},{"name":"ginger","quantity_text":"1 inch","optional":false},{"name":"spring onion","quantity_text":"4","optional":false},{"name":"soy sauce","quantity_text":"2 tbsp","optional":false},{"name":"chili sauce","quantity_text":"1 tbsp","optional":false},{"name":"tomato ketchup","quantity_text":"2 tbsp","optional":false},{"name":"vinegar","quantity_text":"1 tsp","optional":false},{"name":"oil","quantity_text":"for frying","optional":false}]'::jsonb, 'snack', 'vegan', 'Indo-Chinese', 'medium', 'medium'),
  ('Mango Lassi', 'Indian', 5, 2, '1. Blend mango pulp, yogurt, milk, sugar and cardamom until smooth.
2. Add ice and blend again.
3. Pour into glasses and garnish with pistachios.', '[{"name":"mango","quantity_text":"2 ripe","optional":false},{"name":"yogurt","quantity_text":"1 cup","optional":false},{"name":"milk","quantity_text":"1/2 cup","optional":false},{"name":"sugar","quantity_text":"2 tbsp","optional":false},{"name":"cardamom","quantity_text":"1 pinch","optional":true},{"name":"pistachios","quantity_text":"1 tbsp","optional":true},{"name":"ice","quantity_text":"1/2 cup","optional":true}]'::jsonb, 'beverage', 'vegetarian', 'Punjabi', 'easy', 'none'),
  ('Pesarattu', 'Indian', 25, 4, '1. Soak green moong dal 4 hours; grind with ginger, green chili, cumin and salt to a smooth batter.
2. Spread batter thin on a hot greased tawa.
3. Sprinkle chopped onion and drizzle oil; cook until crisp.
4. Fold and serve with ginger chutney or upma.', '[{"name":"green moong dal","quantity_text":"1.5 cups","optional":false},{"name":"ginger","quantity_text":"1 inch","optional":false},{"name":"green chili","quantity_text":"3","optional":false},{"name":"cumin seeds","quantity_text":"1 tsp","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"rice","quantity_text":"2 tbsp","optional":true},{"name":"oil","quantity_text":"3 tbsp","optional":false},{"name":"salt","quantity_text":"to taste","optional":false}]'::jsonb, 'breakfast', 'vegan', 'South Indian', 'easy', 'mild'),
  ('Bisi Bele Bath', 'Indian', 50, 4, '1. Pressure cook rice and toor dal together with turmeric until very soft.
2. Boil carrot, beans, peas and drumstick with tamarind water.
3. Add cooked rice dal, bisi bele bath powder, jaggery and salt; simmer to a thick porridge.
4. Temper ghee with mustard seeds, curry leaves, cashews and dried red chili; pour over.', '[{"name":"rice","quantity_text":"1 cup","optional":false},{"name":"toor dal","quantity_text":"3/4 cup","optional":false},{"name":"carrot","quantity_text":"1","optional":false},{"name":"green beans","quantity_text":"1/2 cup","optional":false},{"name":"green peas","quantity_text":"1/2 cup","optional":false},{"name":"tamarind","quantity_text":"small ball","optional":false},{"name":"bisi bele bath powder","quantity_text":"3 tbsp","optional":false},{"name":"jaggery","quantity_text":"1 tsp","optional":true},{"name":"ghee","quantity_text":"3 tbsp","optional":false},{"name":"mustard seeds","quantity_text":"1 tsp","optional":false},{"name":"curry leaves","quantity_text":"10","optional":false},{"name":"cashews","quantity_text":"10","optional":true}]'::jsonb, 'lunch', 'vegetarian', 'South Indian', 'medium', 'medium'),
  ('Avocado Toast with Poached Egg', 'American', 15, 2, '1. Toast sourdough slices until golden.
2. Mash avocado with lemon juice, salt and chili flakes; spread on toast.
3. Poach eggs in simmering water with a splash of vinegar for 3 minutes.
4. Top toast with eggs, pepper and microgreens.', '[{"name":"sourdough bread","quantity_text":"2 slices","optional":false},{"name":"avocado","quantity_text":"1","optional":false},{"name":"eggs","quantity_text":"2","optional":false},{"name":"lemon","quantity_text":"1/2","optional":false},{"name":"chili flakes","quantity_text":"1/2 tsp","optional":true},{"name":"vinegar","quantity_text":"1 tsp","optional":false},{"name":"black pepper","quantity_text":"to taste","optional":false},{"name":"microgreens","quantity_text":"handful","optional":true}]'::jsonb, 'breakfast', 'eggetarian', 'American', 'easy', 'mild'),
  ('BBQ Pulled Pork Sandwiches', 'American', 480, 6, '1. Rub pork shoulder with paprika, brown sugar, garlic powder, salt and pepper.
2. Slow cook with onion and a splash of apple cider vinegar 8 hours on low.
3. Shred pork and toss with barbecue sauce.
4. Pile onto toasted buns with coleslaw.', '[{"name":"pork shoulder","quantity_text":"1.5 kg","optional":false},{"name":"paprika","quantity_text":"2 tbsp","optional":false},{"name":"brown sugar","quantity_text":"2 tbsp","optional":false},{"name":"garlic powder","quantity_text":"1 tbsp","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"apple cider vinegar","quantity_text":"1/4 cup","optional":false},{"name":"barbecue sauce","quantity_text":"1 cup","optional":false},{"name":"burger buns","quantity_text":"6","optional":false},{"name":"coleslaw","quantity_text":"2 cups","optional":true}]'::jsonb, 'dinner', 'non-vegetarian', 'American', 'easy', 'mild'),
  ('Penne Arrabbiata', 'Italian', 25, 4, '1. Cook penne in salted water until al dente.
2. Gently fry garlic and chili flakes in olive oil.
3. Add crushed tomatoes, salt and simmer 10 minutes.
4. Toss pasta in sauce with parsley and grated parmesan.', '[{"name":"penne","quantity_text":"400 g","optional":false},{"name":"crushed tomatoes","quantity_text":"400 g","optional":false},{"name":"garlic","quantity_text":"4 cloves","optional":false},{"name":"chili flakes","quantity_text":"1 tsp","optional":false},{"name":"olive oil","quantity_text":"3 tbsp","optional":false},{"name":"parsley","quantity_text":"2 tbsp","optional":true},{"name":"parmesan","quantity_text":"1/4 cup","optional":true}]'::jsonb, 'dinner', 'vegetarian', 'Italian', 'easy', 'medium'),
  ('Chicken Piccata', 'Italian', 30, 4, '1. Pound chicken breasts thin, season and dredge in flour.
2. Pan fry in butter and olive oil until golden; remove.
3. Deglaze with white wine, lemon juice, chicken stock and capers; simmer 3 minutes.
4. Return chicken, coat in sauce and top with parsley.', '[{"name":"chicken breast","quantity_text":"4","optional":false},{"name":"all purpose flour","quantity_text":"1/2 cup","optional":false},{"name":"butter","quantity_text":"3 tbsp","optional":false},{"name":"olive oil","quantity_text":"2 tbsp","optional":false},{"name":"lemon","quantity_text":"2","optional":false},{"name":"capers","quantity_text":"3 tbsp","optional":false},{"name":"white wine","quantity_text":"1/2 cup","optional":true},{"name":"chicken stock","quantity_text":"1/2 cup","optional":false},{"name":"parsley","quantity_text":"2 tbsp","optional":true}]'::jsonb, 'dinner', 'non-vegetarian', 'Italian', 'medium', 'none'),
  ('Tiramisu', 'Italian', 30, 6, '1. Whisk egg yolks with sugar over a water bath until pale; fold in mascarpone.
2. Whip cream and fold into the mascarpone mixture.
3. Dip ladyfingers briefly in cooled espresso and layer in a dish with cream.
4. Repeat, dust with cocoa and chill 6 hours.', '[{"name":"mascarpone","quantity_text":"500 g","optional":false},{"name":"ladyfingers","quantity_text":"24","optional":false},{"name":"espresso","quantity_text":"1.5 cups","optional":false},{"name":"eggs","quantity_text":"4","optional":false},{"name":"sugar","quantity_text":"1/2 cup","optional":false},{"name":"heavy cream","quantity_text":"1 cup","optional":false},{"name":"cocoa powder","quantity_text":"2 tbsp","optional":false},{"name":"coffee liqueur","quantity_text":"2 tbsp","optional":true}]'::jsonb, 'dessert', 'eggetarian', 'Italian', 'medium', 'none'),
  ('Miso Soup with Tofu', 'Asian', 15, 2, '1. Simmer dashi stock and add wakame seaweed.
2. Add cubed tofu and warm through.
3. Turn off heat, whisk miso paste with a ladle of broth and stir in.
4. Garnish with spring onion.', '[{"name":"dashi stock","quantity_text":"3 cups","optional":false},{"name":"miso paste","quantity_text":"3 tbsp","optional":false},{"name":"tofu","quantity_text":"150 g","optional":false},{"name":"wakame seaweed","quantity_text":"1 tbsp","optional":false},{"name":"spring onion","quantity_text":"2","optional":false}]'::jsonb, 'lunch', 'vegan', 'Asian', 'easy', 'none'),
  ('Bibimbap', 'Asian', 45, 2, '1. Cook short grain rice.
2. Separately saute spinach, carrot, zucchini, bean sprouts and mushrooms with sesame oil and garlic.
3. Fry eggs sunny side up.
4. Arrange vegetables over rice, top with egg, gochujang and sesame seeds; mix before eating.', '[{"name":"rice","quantity_text":"1.5 cups","optional":false},{"name":"spinach","quantity_text":"2 cups","optional":false},{"name":"carrot","quantity_text":"1","optional":false},{"name":"zucchini","quantity_text":"1","optional":false},{"name":"bean sprouts","quantity_text":"1 cup","optional":false},{"name":"mushrooms","quantity_text":"1 cup","optional":false},{"name":"eggs","quantity_text":"2","optional":false},{"name":"gochujang","quantity_text":"2 tbsp","optional":false},{"name":"sesame oil","quantity_text":"2 tbsp","optional":false},{"name":"garlic","quantity_text":"3 cloves","optional":false},{"name":"sesame seeds","quantity_text":"1 tsp","optional":true}]'::jsonb, 'dinner', 'eggetarian', 'Asian', 'medium', 'medium'),
  ('Falafel Bowl', 'Mediterranean', 40, 4, '1. Blend soaked chickpeas with onion, garlic, parsley, cumin, coriander and baking soda to a coarse paste.
2. Shape into balls and deep fry until crisp and brown.
3. Whisk tahini, lemon juice, garlic and water into a sauce.
4. Serve falafel over salad and rice with tahini drizzle and pickles.', '[{"name":"chickpeas","quantity_text":"2 cups","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"garlic","quantity_text":"4 cloves","optional":false},{"name":"parsley","quantity_text":"1 cup","optional":false},{"name":"cumin powder","quantity_text":"2 tsp","optional":false},{"name":"coriander powder","quantity_text":"1 tsp","optional":false},{"name":"baking soda","quantity_text":"1/2 tsp","optional":false},{"name":"tahini","quantity_text":"1/4 cup","optional":false},{"name":"lemon","quantity_text":"1","optional":false},{"name":"cucumber","quantity_text":"1","optional":true},{"name":"tomato","quantity_text":"2","optional":true},{"name":"oil","quantity_text":"for frying","optional":false}]'::jsonb, 'lunch', 'vegan', 'Mediterranean', 'medium', 'mild'),
  ('Lemon Herb Couscous Salad', 'Mediterranean', 20, 4, '1. Pour boiling stock over couscous, cover 5 minutes and fluff.
2. Dice cucumber, tomato, red onion and bell pepper.
3. Toss couscous with vegetables, parsley, mint, olives and feta.
4. Dress with olive oil, lemon juice, salt and pepper.', '[{"name":"couscous","quantity_text":"1.5 cups","optional":false},{"name":"vegetable stock","quantity_text":"1.5 cups","optional":false},{"name":"cucumber","quantity_text":"1","optional":false},{"name":"tomato","quantity_text":"2","optional":false},{"name":"red onion","quantity_text":"1/2","optional":false},{"name":"bell pepper","quantity_text":"1","optional":false},{"name":"parsley","quantity_text":"1/2 cup","optional":false},{"name":"mint","quantity_text":"1/4 cup","optional":true},{"name":"olives","quantity_text":"1/3 cup","optional":true},{"name":"feta","quantity_text":"100 g","optional":true},{"name":"olive oil","quantity_text":"3 tbsp","optional":false},{"name":"lemon","quantity_text":"1","optional":false}]'::jsonb, 'lunch', 'vegetarian', 'Mediterranean', 'easy', 'none'),
  ('Chicken Enchiladas', 'Mexican', 50, 4, '1. Shred cooked chicken and mix with half the cheese, onion and cumin.
2. Warm tortillas, fill with chicken, roll and place seam down in a baking dish.
3. Pour enchilada sauce over, top with remaining cheese.
4. Bake at 190C for 20 minutes; serve with sour cream and coriander.', '[{"name":"chicken","quantity_text":"500 g","optional":false},{"name":"flour tortillas","quantity_text":"8","optional":false},{"name":"enchilada sauce","quantity_text":"2 cups","optional":false},{"name":"cheddar cheese","quantity_text":"2 cups","optional":false},{"name":"onion","quantity_text":"1","optional":false},{"name":"cumin powder","quantity_text":"1 tsp","optional":false},{"name":"sour cream","quantity_text":"1/2 cup","optional":true},{"name":"coriander leaves","quantity_text":"2 tbsp","optional":true}]'::jsonb, 'dinner', 'non-vegetarian', 'Mexican', 'medium', 'medium'),
  ('Elote Mexican Street Corn', 'Mexican', 20, 4, '1. Grill corn cobs until charred in spots.
2. Mix mayonnaise, sour cream, lime juice and garlic.
3. Brush corn with the mixture.
4. Roll in crumbled cotija cheese, dust with chili powder and serve with lime.', '[{"name":"corn on the cob","quantity_text":"4","optional":false},{"name":"mayonnaise","quantity_text":"1/4 cup","optional":false},{"name":"sour cream","quantity_text":"2 tbsp","optional":false},{"name":"cotija cheese","quantity_text":"1/2 cup","optional":false},{"name":"lime","quantity_text":"2","optional":false},{"name":"chili powder","quantity_text":"1 tsp","optional":false},{"name":"garlic","quantity_text":"1 clove","optional":true},{"name":"coriander leaves","quantity_text":"2 tbsp","optional":true}]'::jsonb, 'snack', 'vegetarian', 'Mexican', 'easy', 'mild'),
  ('Thai Green Curry with Chicken', 'Thai', 35, 4, '1. Fry green curry paste in a little coconut cream until fragrant.
2. Add chicken and stir 3 minutes.
3. Pour in coconut milk, fish sauce and palm sugar; simmer.
4. Add eggplant and bamboo shoots, cook 8 minutes; finish with basil and serve with jasmine rice.', '[{"name":"chicken","quantity_text":"500 g","optional":false},{"name":"green curry paste","quantity_text":"3 tbsp","optional":false},{"name":"coconut milk","quantity_text":"400 ml","optional":false},{"name":"fish sauce","quantity_text":"2 tbsp","optional":false},{"name":"palm sugar","quantity_text":"1 tbsp","optional":false},{"name":"thai eggplant","quantity_text":"1 cup","optional":true},{"name":"bamboo shoots","quantity_text":"1/2 cup","optional":true},{"name":"thai basil","quantity_text":"handful","optional":false},{"name":"jasmine rice","quantity_text":"to serve","optional":false}]'::jsonb, 'dinner', 'non-vegetarian', 'Thai', 'easy', 'hot'),
  ('Kung Pao Chicken', 'Chinese', 30, 4, '1. Marinate diced chicken in soy sauce, rice wine and cornflour.
2. Stir fry dried red chilies and Sichuan peppercorns in oil until fragrant.
3. Add chicken and cook until browned; add garlic, ginger and spring onion.
4. Pour in soy, vinegar, sugar and cornflour slurry; toss with roasted peanuts.', '[{"name":"chicken","quantity_text":"500 g","optional":false},{"name":"peanuts","quantity_text":"1/2 cup","optional":false},{"name":"dried red chili","quantity_text":"8","optional":false},{"name":"sichuan peppercorns","quantity_text":"1 tsp","optional":true},{"name":"soy sauce","quantity_text":"3 tbsp","optional":false},{"name":"rice vinegar","quantity_text":"1 tbsp","optional":false},{"name":"sugar","quantity_text":"1 tbsp","optional":false},{"name":"cornflour","quantity_text":"1 tbsp","optional":false},{"name":"garlic","quantity_text":"4 cloves","optional":false},{"name":"ginger","quantity_text":"1 inch","optional":false},{"name":"spring onion","quantity_text":"4","optional":false},{"name":"oil","quantity_text":"3 tbsp","optional":false}]'::jsonb, 'dinner', 'non-vegetarian', 'Chinese', 'medium', 'hot'),
  ('Chicken Shawarma Wrap', 'Middle Eastern', 45, 4, '1. Marinate chicken thighs in yogurt, lemon, garlic, cumin, paprika, turmeric and cinnamon for 1 hour.
2. Grill or pan sear until charred and cooked; slice thin.
3. Mix garlic sauce from yogurt, garlic and lemon.
4. Fill pita with chicken, pickles, tomato, lettuce and sauce; roll tightly.', '[{"name":"chicken thigh","quantity_text":"600 g","optional":false},{"name":"yogurt","quantity_text":"1/2 cup","optional":false},{"name":"lemon","quantity_text":"1","optional":false},{"name":"garlic","quantity_text":"6 cloves","optional":false},{"name":"cumin powder","quantity_text":"2 tsp","optional":false},{"name":"paprika","quantity_text":"2 tsp","optional":false},{"name":"turmeric","quantity_text":"1/2 tsp","optional":false},{"name":"cinnamon","quantity_text":"1/2 tsp","optional":true},{"name":"pita bread","quantity_text":"4","optional":false},{"name":"pickles","quantity_text":"1/2 cup","optional":true},{"name":"tomato","quantity_text":"2","optional":false},{"name":"lettuce","quantity_text":"1 cup","optional":false}]'::jsonb, 'lunch', 'non-vegetarian', 'Middle Eastern', 'medium', 'mild')
on conflict (name) do nothing;