UPDATE public.recipes SET diet='vegetarian', meal_type='dinner', spice_level='medium' WHERE name='Aloo Gobi' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='mild' WHERE name='Beef & Broccoli' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='medium' WHERE name='Beef Burrito Bowls' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='dinner', spice_level='medium' WHERE name='Black Bean Tacos' AND diet IS NULL;
UPDATE public.recipes SET diet='eggetarian', meal_type='breakfast', spice_level='none' WHERE name='Buttermilk Pancakes' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='lunch', spice_level='none' WHERE name='Caprese Salad' AND diet IS NULL;
UPDATE public.recipes SET diet='vegan', meal_type='dinner', spice_level='hot' WHERE name='Chana Masala' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='lunch', spice_level='none' WHERE name='Chicken Caesar Salad' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='none' WHERE name='Chicken Parmesan' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='mild' WHERE name='Chicken Quesadillas' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='mild' WHERE name='Chicken Teriyaki Stir-Fry' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='hot' WHERE name='Chicken Tikka Masala' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='medium' WHERE name='Chicken Tortilla Soup' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='lunch', spice_level='none' WHERE name='Classic Grilled Cheese' AND diet IS NULL;
UPDATE public.recipes SET diet='eggetarian', meal_type='lunch', spice_level='mild' WHERE name='Egg Drop Soup' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='mild' WHERE name='Garlic Ginger Salmon' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='lunch', spice_level='none' WHERE name='Greek Salad' AND diet IS NULL;
UPDATE public.recipes SET diet='vegan', meal_type='snack', spice_level='mild' WHERE name='Guacamole & Chips' AND diet IS NULL;
UPDATE public.recipes SET diet='eggetarian', meal_type='breakfast', spice_level='medium' WHERE name='Huevos Rancheros' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='lunch', spice_level='none' WHERE name='Hummus & Veggie Wraps' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='none' WHERE name='Lemon Garlic Roast Chicken' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='none' WHERE name='Loaded Baked Potatoes' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='dinner', spice_level='none' WHERE name='Margherita Pizza' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='mild' WHERE name='Mediterranean Baked Cod' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='dinner', spice_level='none' WHERE name='Mushroom Risotto' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='dinner', spice_level='medium' WHERE name='Palak Paneer' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='dinner', spice_level='medium' WHERE name='Red Lentil Dal' AND diet IS NULL;
UPDATE public.recipes SET diet='eggetarian', meal_type='breakfast', spice_level='medium' WHERE name='Shakshuka' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='medium' WHERE name='Shrimp Fajitas' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='medium' WHERE name='Shrimp Pad Thai' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='dinner', spice_level='none' WHERE name='Spaghetti Carbonara' AND diet IS NULL;
UPDATE public.recipes SET diet='eggetarian', meal_type='breakfast', spice_level='none' WHERE name='Spinach & Egg Scramble' AND diet IS NULL;
UPDATE public.recipes SET diet='vegan', meal_type='dinner', spice_level='mild' WHERE name='Tofu & Vegetable Stir-Fry' AND diet IS NULL;
UPDATE public.recipes SET diet='vegetarian', meal_type='dinner', spice_level='none' WHERE name='Tomato Basil Pasta' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='lunch', spice_level='none' WHERE name='Turkey & Avocado Sandwich' AND diet IS NULL;
UPDATE public.recipes SET diet='non-vegetarian', meal_type='lunch', spice_level='mild' WHERE name='Tzatziki Chicken Pita' AND diet IS NULL;
UPDATE public.recipes SET diet='vegan', meal_type='dinner', spice_level='medium' WHERE name='Vegetable Curry with Coconut Milk' AND diet IS NULL;
UPDATE public.recipes SET diet='eggetarian', meal_type='dinner', spice_level='mild' WHERE name='Vegetable Fried Rice' AND diet IS NULL;
UPDATE public.recipes SET diet='eggetarian', meal_type='breakfast', spice_level='none' WHERE name='Zucchini Frittata' AND diet IS NULL;